### ISSUE TITLE
ICCBot fails

### ISSUE THREAD

**Issue by negara** [hanada31/ICCBot#7]
Hi,
I am not able to run ICCBot. 
Upon running, I face: 
`Exception in thread "main" java.lang.NoClassDefFoundError: soot/javaToJimple/LocalGenerator
	at soot.jimple.infoflow.cfg.LibraryClassPatcher.generateMessageObtainMethod(LibraryClassPatcher.java:229)
	at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchMessageObtainImplementation(LibraryClassPatcher.java:124)
	at soot.jimple.infoflow.cfg.LibraryClassPatcher.patchLibraries(LibraryClassPatcher.java:75)
	at soot.jimple.infoflow.android.SetupApplication.initializeSoot(SetupApplication.java:1452)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow_dummy(SetupApplication.java:1793)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow_dummy(SetupApplication.java:1776)
	at main.java.client.cg.CgConstructor.constructDummyMainMethods(CgConstructor.java:112)
	at main.java.client.cg.CgConstructor.analyze(CgConstructor.java:60)
	at main.java.client.cg.CallGraphClient.clientAnalyze(CallGraphClient.java:30)
	at main.java.client.BaseClient.start(BaseClient.java:21)
	at main.java.client.obj.target.ctg.CTGClient.clientAnalyze(CTGClient.java:59)
	at main.java.client.BaseClient.start(BaseClient.java:21)
	at main.java.MainClass.startAnalyze(MainClass.java:83)
	at main.java.MainClass.main(MainClass.java:52)
Caused by: java.lang.ClassNotFoundException: soot.javaToJimple.LocalGenerator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 14 more
`
Which I believe has something to do with the different versions of soot in the lib and maven.
Could you please share a jar file of the tool in the releases section?

**Comment by hanada31** [comment]
Hi,
Thanks for pointing out this.
I have updated the jar file. Please try to checkout the newest version of the main branch and try with the command 
`python .\scripts\runICCBot.py [apkFolder] [resultFolder]`.
